<template>
    <div>
        <top_side :position=3 />
        <!-- <banner :info="banner[2]" /> -->
        <div>
            <tiny-carousel height="92vh" width="100vw" @change="handleChange" arrow="never" autoplay> 
                <tiny-carousel-item class="carousel-item-demo" v-for="(item,index) in items" :key="index">
                    <img :id="item.img_id" :src="item.src">
                    <div :id="item.text_id" :class="inAni[index]?item.ani:''">{{ item.text }}</div>
                </tiny-carousel-item>
            </tiny-carousel>
        </div>
    </div>
</template>

<script>
import { Carousel as TinyCarousel, CarouselItem as TinyCarouselItem } from '@opentiny/vue'
import banner from '../components/banner.vue';
import top_side from '../components/top_side.vue';
export default {
    components:{
        top_side,banner,TinyCarousel,TinyCarouselItem
    },
    data() {
        return {
            banner:['首页', '健康咨询','我们的服务', '词云视图', '数据查询'],
            items:[{
                src:"https://cdn.pixabay.com/photo/2015/05/02/14/05/wheelchair-749985_1280.jpg",
                text:"残疾人援助",
                text_id:"textBox1",
                img_id:"imgBox1",
                ani:"scale-up-bl"
            },
            {
                src:"https://cdn.pixabay.com/photo/2019/11/04/11/38/medical-4600914_1280.jpg",
                text:"先进的技术",
                text_id:"textBox2",
                img_id:"imgBox2",
                ani:"swing-in-top-fwd"
            },
            {
                src:"https://cdn.pixabay.com/photo/2014/10/14/09/20/first-aid-487991_1280.jpg",
                text:"人道主义救助",
                text_id:"textBox3",
                img_id:"imgBox3",
                ani:"bounce-in-top"
            },
            {
                src:"https://cdn.pixabay.com/photo/2014/12/10/20/48/laboratory-563423_1280.jpg",
                text:"强大的科研",
                text_id:"textBox4",
                img_id:"imgBox4",
                ani:"tilt-in-fwd-tr"
            }
            ],
            inAni:[true,false,false,false]
        }
    },
    methods:{
        handleChange(value,oldValue){
            this.inAni[value] = true
            this.inAni[oldValue] = false
        },
    }
}
</script>

<style scoped>
.carousel-item-demo:nth-child(2n) {
  background-color: #fafafa;
}

.carousel-item-demo:nth-child(2n + 1) {
  background-color: #edf0f3;
}
#textBox1{
    width: 25vw;
    height: 25vh;
    /* background: rgba(142, 142, 142, 0.764); */
    position: absolute;
    bottom: 10vh;
    font-family: FZShuTi;
    font-size: 4vw;
    color: #e3fdfd;
    text-shadow:0px 1px 0px #c0c0c0,
	 0px 2px 0px #b0b0b0,
	 0px 3px 0px #a0a0a0,
	 0px 4px 0px #909090,
	 0px 5px 10px rgba(0, 0, 0, .9);
}
#imgBox1{
    width: 100vw;
    height: 92vh;
}
#textBox2{
    width: 25vw;
    height: 25vh;
    /* background: rgba(255, 255, 255, 0.94); */
    position: absolute;
    bottom: 10vh;
    font-family: FZShuTi;
    font-size: 4vw;
    color: #fefefe;
    text-shadow:0px 1px 0px #c0c0c0,
	 0px 2px 0px #b0b0b0,
	 0px 3px 0px #a0a0a0,
	 0px 4px 0px #909090,
	 0px 5px 10px rgba(0, 0, 0, .9);
}
#imgBox2{
    width: 100vw;
    height: 92vh;
}
#textBox3{
    width: 30vw;
    height: 92vh;
    background: #e3fdfd;
    position: absolute;
    top: 0vh;
    right: 10vw;
    text-shadow: 0 -1px 1px #eee;
    writing-mode:vertical-rl;
    font-size: 15vh;
    font-family: FZShuTi;
}
#imgBox3{
    width: 60vw;
}
#textBox4{
    width: 30vw;
    height: 50vh;
    /* background: #e3fdfd; */
    position: absolute;
    bottom: 0vh;
    right: 3vw;
    text-shadow: 0 -1px 1px #eee;
    writing-mode:vertical-rl;
    font-size: 15vh;
    font-family: FZShuTi;
}
#imgBox4{
    width: 100vw;
    height: 92vh;
}


.tilt-in-fwd-tr {
	-webkit-animation: tilt-in-fwd-tr 0.9s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: tilt-in-fwd-tr 0.9s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-5-4 11:47:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tilt-in-fwd-tr
 * ----------------------------------------
 */
 @-webkit-keyframes tilt-in-fwd-tr {
  0% {
    -webkit-transform: rotateY(20deg) rotateX(35deg) translate(300px, -300px) skew(-35deg, 10deg);
            transform: rotateY(20deg) rotateX(35deg) translate(300px, -300px) skew(-35deg, 10deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
            transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
    opacity: 1;
  }
}
@keyframes tilt-in-fwd-tr {
  0% {
    -webkit-transform: rotateY(20deg) rotateX(35deg) translate(300px, -300px) skew(-35deg, 10deg);
            transform: rotateY(20deg) rotateX(35deg) translate(300px, -300px) skew(-35deg, 10deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
            transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
    opacity: 1;
  }
}

.swing-in-top-fwd {
	-webkit-animation: swing-in-top-fwd 0.5s 0.5s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
	        animation: swing-in-top-fwd 0.5s 0.5s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-5-4 12:3:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-top-fwd
 * ----------------------------------------
 */
 @-webkit-keyframes swing-in-top-fwd {
  0% {
    -webkit-transform: rotateX(-100deg);
            transform: rotateX(-100deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg);
            transform: rotateX(0deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 1;
  }
}
@keyframes swing-in-top-fwd {
  0% {
    -webkit-transform: rotateX(-100deg);
            transform: rotateX(-100deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg);
            transform: rotateX(0deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 1;
  }
}


.scale-up-bl {
	-webkit-animation: scale-up-bl 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-bl 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-5-4 11:8:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-bl
 * ----------------------------------------
 */
 @-webkit-keyframes scale-up-bl {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
  }
}
@keyframes scale-up-bl {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
  }
}



.bounce-in-top {
	-webkit-animation: bounce-in-top 1.1s ;
	        animation: bounce-in-top 1.1s ;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-5-3 21:34:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
 @-webkit-keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
            transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
            transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
            transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
            transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
            transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
            transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
            transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
            transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}

</style>